In [1]:
import threading
import queue
import cProfile
import itertools
import numpy as np

In [2]:
in_queue = queue.Queue()
out_queue = queue.Queue()

In [3]:
def random_number_threading():
    while True:
        n = in_queue.get()
        if n == "STOP":
            return
        random_numbers = np.random.rand(n)
        out_queue.put(random_numbers)

In [4]:
def generate_random_numbers(show_output, up_to):
    thread = threading.Thread(target=random_number_threading)
    thread.start()
    for i in range(up_to):
        in_queue.put(i)
        random_nums = out_queue.get()
        if show_output:
            print(random_nums)
    in_queue.put("STOP")
    thread.join()

In [5]:
generate_random_numbers(True, 10)

[]
[0.33463445]
[0.2365773 0.7472175]
[0.57472817 0.40924828 0.41383936]
[0.37073834 0.03778989 0.15214711 0.93295525]
[0.80880402 0.63801473 0.74398502 0.21178209 0.17550453]
[0.86432564 0.18970221 0.19424957 0.79010612 0.84340262 0.49685915]
[0.46660158 0.09442849 0.00693373 0.49306517 0.72678374 0.20271225
 0.73219864]
[0.03087201 0.04441938 0.4882512  0.45264701 0.23752562 0.51168345
 0.85740641 0.40150812]
[0.9820383  0.61639512 0.32275108 0.19046151 0.23978491 0.95658956
 0.7432129  0.29416516 0.8832993 ]


In [6]:
cProfile.run("generate_random_numbers(False, 20000)")

         740059 function calls in 2.418 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.044    0.044    2.418    2.418 <ipython-input-4-2824eefd5a03>:1(generate_random_numbers)
        1    0.000    0.000    2.418    2.418 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 _weakrefset.py:38(_remove)
        1    0.000    0.000    0.000    0.000 _weakrefset.py:81(add)
    20001    0.046    0.000    0.155    0.000 queue.py:121(put)
    20000    0.109    0.000    2.219    0.000 queue.py:153(get)
    40000    0.014    0.000    0.020    0.000 queue.py:208(_qsize)
    20001    0.008    0.000    0.010    0.000 queue.py:212(_put)
    20000    0.008    0.000    0.011    0.000 queue.py:216(_get)
        1    0.000    0.000    0.000    0.000 threading.py:1017(_wait_for_tstate_lock)
        2    0.000    0.000    0.000    0.000 threading.py:1095(daemon)
        1    0.000    0.000    0.000    0.000 thread